### ISSUE TITLE
登录App之后，什么场合需要再次登录？

### ISSUE THREAD

**Issue by oizhaolei** [oizhaolei/yida-lize-issues#2]

**Comment by oizhaolei** [comment]
当前开发阶段， 2次登录超过24小时， 就失效，需要重新登录。
这个24小时，可以调整。

**Comment by st8117** [comment]
开发阶段无所谓，客户实际使用的时候，哪些情况需要重新登录？
1：手动退出之后
2：一定时间之后？这个时间是多长时间？
我担心几分钟或者几秒钟的话，每天可能发生一个人重复发验证码，毕竟是花钱的东西，总发，总登录不太好。

**Comment by oizhaolei** [comment]
- 手动退出之后
- 本次登录距离上一次登录，超过24小时
需要重新登录

这个24小时，可以调节成为1个月，半年。。。

**Comment by st8117** [comment]
OK
