### ISSUE TITLE
功能强调：检索功能是企业表全部检索

### ISSUE THREAD

**Issue by st8117** [oizhaolei/yida-lize-issues#6]
也就是说企业有关的表，输入关键字之后，只要有匹配的，就把信息显示出来。

**Comment by oizhaolei** [comment]
数据量是多大。
担心full-text检索会拖垮整个数据库。

需不需要上一个大数据系统，比如ElasticSearch什么的？

**Comment by st8117** [comment]
一共最多就是2000人，所以企业最多也就1000条，
这样的量mango能不能胜任？

**Comment by oizhaolei** [comment]
1000条数据的情况下，全文检索可以。
